repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: mixed-line-ending
      - id: debug-statements

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.2
    hooks:
      - id: pycln
        language_version: python3
        stages: [commit]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.13.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --extend-ignore=E203]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [-c, .yamllint]
        exclude: 'deployments/helm'

  - repo: https://github.com/instrumenta/kubeval
    rev: 0e2c65b
    hooks:
      - id: kubeval
        files: ^deployments/k8s/.*\.yaml$

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
        files: ^deployments/terraform/

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.17.0
    hooks:
      - id: terraform-docs-go
        files: ^deployments/terraform/modules/
        args: [--sort-by-required]

  - repo: local
    hooks:
      - id: molt-scanner
        name: Molt Vulnerability Scanner
        entry: ./scripts/pre-commit/molt-scanner.sh
        language: script
        pass_filenames: false
        stages: [commit]

default_language_version:
  python: python3.11
  go: "1.21"
  rust: "1.70.0"
