---
collections:
  - name: community.general
    version: ">=7.0.0"
  - name: ansible.posix
    version: ">=1.4.0"
  - name: community.docker
    version: ">=3.4.0"
  - name: kubernetes.core
    version: ">=2.4.0"

roles:
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.kubernetes
    version: 4.0.0
