all:
  children:
    kubernetes_masters:
      hosts:
        k8s-master-staging:
          ansible_host: 10.1.1.10
          ansible_port: 22
      vars:
        node_type: control-plane
        
    kubernetes_workers:
      hosts:
        k8s-worker-staging-01:
          ansible_host: 10.1.2.10
        k8s-worker-staging-02:
          ansible_host: 10.1.2.11
      vars:
        node_type: worker
        
    ceph_monitors:
      hosts:
        ceph-mon-staging:
          ansible_host: 10.1.3.10
      vars:
        ceph_role: monitor
        
    ceph_osds:
      hosts:
        ceph-osd-staging-01:
          ansible_host: 10.1.3.20
        ceph-osd-staging-02:
          ansible_host: 10.1.3.21
      vars:
        ceph_role: osd
        
  vars:
    environment: staging
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/kubric_staging_rsa
